templates [ci skip] Updating packages templates.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,16 +7,18 @@ workflows:
   version: 2
   test:
     jobs:
-    - test-37:
+    - test-37-src:
         context: << pipeline.parameters.context_name >>
-    - test-38:
+    - test-38-src:
         context: << pipeline.parameters.context_name >>
-    - test-39:
+    - test-39-src:
         context: << pipeline.parameters.context_name >>
-    - test-310:
+    - test-310-src:
+        context: << pipeline.parameters.context_name >>
+    - test-310-bin:
         context: << pipeline.parameters.context_name >>
 jobs:
-  test-37:
+  test-37-src:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -27,7 +29,6 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: contracts,contracts_tests
       TEST_PACKAGES: contracts_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
     docker:
     - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.7:${Z_DISTRO}
       auth:
@@ -48,6 +49,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -56,6 +59,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -63,6 +68,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -75,6 +82,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -117,6 +126,8 @@ jobs:
     - run:
         name: contracts_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           mkdir -p out/test-results
           xunit_output=$PWD/out/test-results/nose-${CIRCLE_NODE_INDEX}-contracts_tests-xunit.xml
@@ -163,7 +174,7 @@ jobs:
           chmod +x codecov
           ./codecov  
     resource_class: small
-  test-38:
+  test-38-src:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -174,7 +185,6 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: contracts,contracts_tests
       TEST_PACKAGES: contracts_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
     docker:
     - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.8:${Z_DISTRO}
       auth:
@@ -195,6 +205,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -203,6 +215,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -210,6 +224,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -222,6 +238,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -264,6 +282,8 @@ jobs:
     - run:
         name: contracts_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           mkdir -p out/test-results
           xunit_output=$PWD/out/test-results/nose-${CIRCLE_NODE_INDEX}-contracts_tests-xunit.xml
@@ -310,7 +330,7 @@ jobs:
           chmod +x codecov
           ./codecov  
     resource_class: small
-  test-39:
+  test-39-src:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -321,7 +341,6 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: contracts,contracts_tests
       TEST_PACKAGES: contracts_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
     docker:
     - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.9:${Z_DISTRO}
       auth:
@@ -342,6 +361,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -350,6 +371,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -357,6 +380,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -369,6 +394,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -411,6 +438,8 @@ jobs:
     - run:
         name: contracts_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           mkdir -p out/test-results
           xunit_output=$PWD/out/test-results/nose-${CIRCLE_NODE_INDEX}-contracts_tests-xunit.xml
@@ -457,7 +486,7 @@ jobs:
           chmod +x codecov
           ./codecov  
     resource_class: small
-  test-310:
+  test-310-src:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -468,7 +497,6 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: contracts,contracts_tests
       TEST_PACKAGES: contracts_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
     docker:
     - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.10:${Z_DISTRO}
       auth:
@@ -489,6 +517,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -497,6 +527,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -504,6 +536,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -516,6 +550,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -558,6 +594,172 @@ jobs:
     - run:
         name: contracts_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          set -euxo pipefail
+          TEST_MODULES=$(circleci tests split <.circleci/contracts_tests.tests)
+          echo "TEST_MODULES=[$TEST_MODULES]"
+          if [ -z "$TEST_MODULES" ]; then
+            echo "\$TEST_MODULES is empty"
+            exit 0
+          else
+            echo "\$TEST_MODULES is NOT empty"
+          fi
+          mkdir -p out/test-results
+          xunit_output=$PWD/out/test-results/nose-${CIRCLE_NODE_INDEX}-contracts_tests-xunit.xml
+          timeout 30m nose2 --with-coverage \
+              --plugin nose2.plugins.junitxml \
+              --junit-xml \
+              --junit-xml-path ${xunit_output} \
+              $TEST_MODULES
+          # TODO: cover packages
+    - run:
+        name: post-circle-tests
+        command: |
+          TARGET=post-circle-tests
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+
+    - store_test_results:
+        path: out/test-results
+
+    - run:
+        name: Coverage report
+        when: always
+        command: |
+          coverage combine || true
+          coverage html -d out/coverage/${CIRCLE_NODE_INDEX} || true
+          coverage xml || true
+
+    - store_artifacts:
+        path: out/coverage
+        destination: coverage
+
+    - store_artifacts:
+        path: out/tests
+        destination: tests
+
+    - run:
+        name: CodeCov
+        when: always
+        command: |
+          curl -Os https://uploader.codecov.io/latest/linux/codecov
+          chmod +x codecov
+          ./codecov  
+    resource_class: small
+  test-310-bin:
+    #    machine: true
+    #    resource_class: zuper-ci-ns/my-resource-class
+    environment:
+      COLUMNS: '160'
+      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      CONTEXT_NAME: << pipeline.parameters.context_name >>
+      DEPS_INSTALL_TIMEOUT: 10m
+      COVER_PACKAGES: contracts,contracts_tests
+      TEST_PACKAGES: contracts_tests
+    docker:
+    - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.10:${Z_DISTRO}
+      auth:
+        username: $DOCKER_USERNAME
+        password: $DOCKER_PASSWORD
+    working_directory: ~/repo
+    steps:
+    - checkout
+    - run:
+        name: Build statistics
+        command: |
+          mkdir -p build-stats
+          # env | sort | tee  build-stats/env.txt
+          env | sort
+    - store_artifacts:
+        path: build-stats
+        destination: build-stats
+    - run:
+        name: Install deps
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
+          python3 -m pip install -U pip
+          timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
+          rm .requirements.txt
+
+    - run:
+        name: Install testing deps
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
+          timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
+          rm .requirements_tests.txt
+
+    - run:
+        name: Python stats
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          pipdeptree | tee  build-stats/pipdeptree.txt
+          python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
+          python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
+          python3 -m pip cache list | tee  build-stats/pip-cache.txt
+
+    - store_artifacts:
+        path: build-stats
+        destination: build-stats
+
+    - run:
+        name: setup.py develop
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          python3 -m pip install -e . --prefix ~/.local --no-deps
+
+    - run:
+        name: Make docs
+        command: |
+          FILE=src/conf.py
+          mkdir -p out/docs
+          if test -f "$FILE"; then
+              sphinx-build src out/docs
+          fi
+
+    - store_artifacts:
+        path: out/docs
+        destination: docs
+    - run:
+        background: true
+        name: services
+        command: |
+          TARGET=services
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+    - run:
+        name: pre-circle-tests
+        command: |
+          TARGET=pre-circle-tests
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+    # - run:
+    #     name: Notebooks
+    #     command: |
+    #       make -C notebooks cleanup all
+
+
+    - run:
+        name: contracts_tests
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           TEST_MODULES=$(circleci tests split <.circleci/contracts_tests.tests)
           echo "TEST_MODULES=[$TEST_MODULES]"
@@ -613,4 +815,4 @@ jobs:
           ./codecov  
     resource_class: small
 
-# sigil 91d6335202725e050a40aa71076ec0e7
+# sigil 380bea152d0384b5f1e2f5058929ca0b
